readme: 
 - README.md
credits: 
 - Translations/credits.txt
en: 
 - Translations/English (default)/**/*
cs: 
 - Translations/cs/**/*
da: 
 - Translations/da/**/*
de: 
 - Translations/de/**/*
es: 
 - Translations/es/**/*
fi: 
 - Translations/fi/**/*
fr: 
 - Translations/fr/**/*
hu: 
 - Translations/hu/**/*
it: 
 - Translations/it/**/*
ja: 
 - Translations/ja/**/*
ko: 
 - Translations/ko/**/*
lv: 
 - Translations/lv/**/*
nb: 
 - Translations/nb/**/*
nl: 
 - Translations/nl/**/*
pl: 
 - Translations/pl/**/*
pt-BR: 
 - Translations/pt-BR/**/*
pt: 
 - Translations/pt/**/*
ru: 
 - Translations/ru/**/*
sk: 
 - Translations/sk/**/*
th: 
 - Translations/th/**/*
tr: 
 - Translations/tr/**/*
uk: 
 - Translations/uk/**/*
zh-Hans: 
 - Translations/zh-Hans/**/*
zh-Hant: 
 - Translations/zh-Hant/**/*
